### PR TITLE
Update my work

### PR DESCRIPTION
**Pull request by asoares1000**
### Description

Update my work section

- [x] title

### Review

Add here all the descriptions that you think it will be useful and valueble to this issue.

### Pre-merge checklist

Add screenshots case needs.

### Screenshots

| Before | After |
| ------ | ----- |
| Image   | Image |

### CODE REVIEW

**Review by assoares2014 — COMMENTED** [review]
other background

**Review by asoares1000 — COMMENTED** [review]
changes finished

**Review by assoares2014 — CHANGES_REQUESTED** [review]
change to black

**Review by assoares2014 — APPROVED** [review]
ok. Very good!

**Pull request merged**
